### ISSUE TITLE
Configure: Error in Build 

### ISSUE THREAD

**Issue by domis4** [jasonmc/forked-daapd#116]
im trying to build the latest source on my raspberry pi using raspbian wheezy

i strictly followed your build instructions in https://github.com/jasonmc/forked-daapd/issues/111
and installed all dependencies as listed in http://gyfgafguf.dk/raspbian/source/forked-daapd_0.19.10.git5a0879d-1.dsc (should be the latest). 
`autoreconf -vi`
works without errors or warnings, but 
`./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-flac --enable-itunes`
exits with error:
`configure: error: Package requirements ( libavformat libavcodec libswscale libavutil libavfilter ) were not met: No Package 'libavfilter' found`

altough it should already be installed, as i followed the guide https://wiki.ubuntuusers.de/Libav
`apt-get install libav-tools`

**Comment by ejurgensen** [comment]
Consider using my fork (https://github.com/ejurgensen/forked-daapd), and following these instructions: https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL

**Comment by domis4** [comment]
thank you, the install process went on like a charm. Looks like i mixed your and this repository and thought it where the same.
