### ISSUE TITLE
Using remote causes lockup

### ISSUE THREAD

**Issue by nickwales** [jasonmc/forked-daapd#28]
Even using a very small music collection I get major issues using an iphone with remote (ver 1.3.3) on fedora (compiled forked-daapd-0.12) 

I can browse albums / songs just fine, but pressing play does nothing, the debug log shows no errors as such, it just looks like it is starting to play. 

After about 20 seconds I then get a message on the iphone saying the library is no longer available, iTunes can no longer connect and the process requires a forceful kill.

Could this be my local audio being problematic? I have the default setup in the conf, would be great to set one of my two airports to be the default output, but it doesn't pick those up before it breaks.

**Comment by peterjc** [comment]
Have you tried running forked-daapd at a more verbose debug level?

**Comment by nickwales** [comment]
Its already running at 'spam'!
