### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by codezomb** [jasonmc/forked-daapd#29]
I've been looking for a replacement for mt-daapd for ever, and I'm pleased to see this repository. However, I had a question. Does this support streaming to the apple tv? This is a huge thing as my library has tons of movies, and such purchased on iTunes, and I just wanted to check before I opened up this can of worms :P

**Comment by peterjc** [comment]
It doesn't support "Home Sharing", so you can't browse the media from the Apple TV.

However, with an iPod/etc and the Apple Remote iOS application you can browse the media on the forked-daapd server, and use AirPlay to send it to the Apple TV. That seems to work with music, not tried video yet...

**Comment by knoopx** [comment]
@peterjc does the Remote.app still work with forked-daapd? Because it is trying to do a pin-based pairing with iTunes and forked-daapd seems to not support that...

**Comment by peterjc** [comment]
I've not tried for ages - I've been using Apple's iTunes Match service instead, which lets me stream my music to the AppleTV or recent iOS device (but for an annual fee). It is entirely possible that Apple have revised their protocol again, and more reverse engineering may be needed.

**Comment by knoopx** [comment]
thanks @peterjc, I'll rather try to reverse "home sharing" instead :)
