### ISSUE TITLE
Does libevent2 break forked-daapd?

### ISSUE THREAD

**Issue by LarsFronius** [jasonmc/forked-daapd#38]
Hi,
I am using forked-daapd on Arch Linux which I think is one of the first distributions that switched from libevent1.4 to libevent2.
Unfortunately forked-daapd stopped working after the switch to libevent2.
Is it possible, that there is a coherence between those two events? Or is this impossible and my forked-daapd server stopped working for other reasons?

**Comment by niQo** [comment]
I can confirm that forked-daapd does not work with libevent 2.0.10, but fine with libevent 1.4.14b.

with libevent 2.0 I have this line in log file, and clients can not access to forked_daapd library :
event: event_del: event has no event_base set.

**Comment by tallship** [comment]
I'm getting this when I first open tmux at the very top of the screen. Same message: "[warn] event_del: event has no event_base set.", with libevent-2.0.10-x86_64-1_SBo

tmux is working at this point, although I have concerns about the stability of some important tasks I'll be attending to. Are my tmux sessions likely to crash on me in the middle of big mozilla (i.e., non-trivial) compiles and such?

Should I just be forgetting about tmux and going back to screen?

Thanks :)
