### ISSUE TITLE
remote pairing

### ISSUE THREAD

**Issue by billy27607** [jasonmc/forked-daapd#41]
I have discovered that the size of your collection affects pairing success. After many attempts and failures at paring, I created a collection with just a couple of songs and was successful immediately with a couple of devices. I suppose that it could have to do with the time it takes to look through the library to find a .remote file. Would it be reasonable to designate a place for the pairing data that could be looked at more often?

**Comment by alanpuccinelli** [comment]
Interesting. Are you getting an error message at all when your pairing fails? I keep getting a Remote not known from mDNS even though I'm absolutely sure the name is correct. I'll have to try a smaller library and report back. Trying to use 0.14 with an iPad

**Comment by billy27607** [comment]
I get that message if I restart the forked-daapd daemon with a .remote file in the library. This happens regardless of the pairing status...

Here is how I have been successful. 
1. Try pairing with a very small library or wait until the daemon scans everything. I have 40,000+ songs and that initial scan takes a while. 
2. Start the daemon with no .remote and let it finish scanning. 
3. Start the iPhone remote app, choose add library and then get the code. If you are running avahi-browse you should see it show up. 
4. Prepare a .remote file in your home directory and move it into the library... I think that the temp file when editing directly in the library may confuse things...

Should go ahead and pair.  I have been successful consistently like this.  

Then delete the .remote file in the library...

Good luck. 

Billy

**Comment by alanpuccinelli** [comment]
That did it. Thanks for the tip. This should be added to the INSTALL readme
for better clarity.
