### ISSUE TITLE
Error compiling on FreeNAS (FreeBSD 7.3-RELEASE-p4)

### ISSUE THREAD

**Issue by orviwan** [jasonmc/forked-daapd#60]
I've been battling through getting all of the prerequisites and libraries installed and I've finally made it to the point where I can 'gmake install', but I'm getting the following error:

```
avio_evbuffer.o `test -f 'avio_evbuffer.c' || echo './'`avio_evbuffer.c
In file included from avio_evbuffer.c:30:
avio_evbuffer.h:5: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
avio_evbuffer.h:9: error: expected ')' before '*' token
avio_evbuffer.c:57: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
avio_evbuffer.c:98: error: expected ')' before '*' token
gmake[2]: *** [forked_daapd-avio_evbuffer.o] Error 1
gmake[2]: Leaving directory `/usr/local/orv/forked-daapd/src'
gmake[1]: *** [install] Error 2
gmake[1]: Leaving directory `/usr/local/orv/forked-daapd/src'
gmake: *** [install-recursive] Error 1
```

I'm using the git source from yesterday.

I'd be grateful for any suggestions.

Thanks

**Comment by orviwan** [comment]
I resolved this by compiling and installing ffmpeg 8.

**Comment by bubbleg5** [comment]
Hello Orviwan, just use FreeNAS, I read the potential of the tool forked-daapd, I'm not very familiar with the compilation, you can help me to install it?
FreeBSD 7.3-RELEASE-p7 (revision 199506)

bubbleg5
