### ISSUE TITLE
"ffmpeg: Header missing"?

### ISSUE THREAD

**Issue by pcace** [jasonmc/forked-daapd#64]
Hi,

i just "updated" from mt-daapd to forked-daapd. I discovered thousands of log messages like:

"ffmpeg: Header missing"

Whats wrong there?!

Im Using Debian wheezy, forked-daapd 0.18 and ffmpeg N-32141-g4becc86 (build today...)
FFmpeg was build like that:

ffmpeg version N-32141-g4becc86, Copyright (c) 2000-2011 the FFmpeg developers
  built on Aug 29 2011 11:38:13 with gcc 4.6.1
  configuration: --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-nonfree --enable-postproc --enable-version3 --enable-x11grab
  libavutil    51. 14. 0 / 51. 14. 0
  libavcodec   53. 12. 0 / 53. 12. 0
  libavformat  53. 10. 0 / 53. 10. 0
  libavdevice  53.  3. 0 / 53.  3. 0
  libavfilter   2. 35. 0 /  2. 35. 0
  libswscale    2.  0. 0 /  2.  0. 0
  libpostproc  51.  2. 0 / 51.  2. 0

in the folder which forked-daapd scanns are about 100000 mp3s but only 80000 are shown in itunes!?
I also tried rebuilding all mp3 Tags to id3 v 2.3 by running "find . -iname "*.mp3" -print0 | xargs -0 eyeD3 --to-v2.3 --set-encoding=latin1 --force-update" several times. 

Where can i find the Problem now?! 

Thanks!

**Comment by tvannahl** [comment]
Are there any solutions or debugs for this problem, yet?
