### ISSUE TITLE
GPERF issue on FreeBSD

### ISSUE THREAD

**Issue by hukl** [jasonmc/forked-daapd#72]
Hey I got it as far as:

gmake[1]: Entering directory `/usr/local/src/forked-daapd/forked-daapd/src'
antlr3 -depend DAAP2SQL.g > DAAP2SQL.u
antlr3 -depend DAAP.g > DAAP.u
antlr3 -depend RSP2SQL.g > RSP2SQL.u
antlr3 -depend RSP.g > RSP.u
gmake[1]: Leaving directory`/usr/local/src/forked-daapd/forked-daapd/src'
gmake[1]: Entering directory `/usr/local/src/forked-daapd/forked-daapd/src'
antlr3  DAAP.g
antlr3  RSP.g
if gperf daap_query.gperf > daap_query_hash.c.tmp; then \
        mv daap_query_hash.c.tmp daap_query_hash.c; \
    elif gperf --version >/dev/null 2>&1; then \
        rm daap_query_hash.c.tmp; \
        exit 1; \
    else \
        rm daap_query_hash.c.tmp; \
        touch daap_query_hash.c; \
    fi
internal error, l != '{' on line 129 in file /usr/src/gnu/usr.bin/gperf/../../../contrib/gperf/src/key-list.ccgmake[1]: *** [daap_query_hash.c] Error 1
gmake[1]: Leaving directory`/usr/local/src/forked-daapd/forked-daapd/src'
gmake: **\* [install-recursive] Error 1

Any ideas?

**Comment by pipian** [comment]
Provided that you have the latest gperf built out of your ports tree (should be 3.0.3), you just need to specify the environment variable GPERF="/usr/local/bin/gperf" at configure-time.  Otherwise you'll be building with the default system gperf (2.7.2).

**Comment by hukl** [comment]
Okay I got a whole lot further but now it is complaining about:

forked_daapd-main.o: In function `main':
main.c:(.text+0x43b): undefined reference to`register_ffmpeg_evbuffer_url_protocol'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: **\* [forked-daapd] Error 1
gmake[2]: Leaving directory `/usr/local/src/forked-daapd/forked-daapd/src'
gmake[1]: *** [install] Error 2
gmake[1]: Leaving directory`/usr/local/src/forked-daapd/forked-daapd/src'
gmake: **\* [install-recursive] Error 1

**Comment by hukl** [comment]
hah i did it - never mind - thnx

**Comment by pipian** [comment]
Did you end up patching the build system (e.g. as I did in https://github.com/pipian/forked-daapd/commit/420cb1c8c10fbff23148e0c8b18dab8ccebe5733) or just the Makefile?

**Comment by catslab** [comment]
I have the same trouble, installed ffmepg-devel and patched the configure.in, no way, still stuck on 
forked_daapd-main.o: In function `main':
main.c:(.text+0x4e5): undefined reference to`register_ffmpeg_evbuffer_url_protocol'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Commented out in main.c and went trhu

**Comment by chave** [comment]
i'm having the same issue as well. Anyone care elaborate on fixing the issue?

**Comment by hukl** [comment]
I just installed ffmpeg-dev if i remember correctly. but hey - forked-daapd is really not worth the effort - i'm back on the latest patch of firefly daapd and it works good enough and doesn't come with an entire desktop linux as dependency. Compared to this dependency mess, writing your own streaming server should be really easy ;)
