### ISSUE TITLE
Run without avahi

### ISSUE THREAD

**Issue by vixducis** [jasonmc/forked-daapd#95]
I'm trying to setup forked-daapd, but i'd prefer it if i could run it without avahi (or rather define my own avahi service instead of using the dbus api). 

The reason is that i want a netatalk share for my time machine backups and a samba share for the symbolic link support (netatalk doesn't support symlinks). Those two are defined as different services in avahi. To make that work, i have to disable avahi's dbus api, or else netatalk tends to take over all the services (osx prefers afp over smb).

 If I now try to start forked-daapd, it just doesn't. Forked-daapd requires avahi's dbus api to be enabled and running. Is there a way to succesfully start forked-daapd without avahi's dbus enabled?

**Comment by elwertk** [comment]
Works without problems for me (forked daapd, netatalk for afp and samba) with this little tweak:

```
/etc/avahi/services# more cifs.service
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>
    <name replace-wildcards="yes">%h-SERVER</name>
    <service>
        <type>_smb._tcp</type>
        <port>445</port>
    </service>
    <service>
         <type>_device-info._tcp</type>
         <port>0</port>
         <txt-record>model=Xserve</txt-record>
    </service>
</service-group>
```

This will enable to distinguish between afp and smb services. AFP will announce itself as YOURSERVERNAME and smb shares as YOURSERVER-NAME in finder on your mac. Also timemachine setup works fine if the share is configured correctly.
